### ISSUE TITLE
Whitelisting broken

### ISSUE THREAD

**Issue by kaimi** [Lumbridge/SmiteMixerCodeRedeemer#12]
When I enable whitelisting, it doesn’t grab any codes whatsoever. If I disable whitelisting, I get codes from users on my whitelist (obviously), but they are listed as not whitelisted in the log.

```
[2018-03-29 20:11:14] Code: APMCB42503C980326 added to active codes (Grabbed from non-whitelisted user: Scottybot.
```

**Comment by kaimi** [comment]
Something made it refresh the whitelist …

```
[2018-03-29 20:33:20] Code: APYSC655FF1980326 added to active codes (Grabbed from whitelisted user: Scottybot.
```

Haven’t tested turning it back on yet.

**Comment by Lumbridge** [comment]
Can you confirm whitelisting issues in latest version? (v1.0.4)

**Comment by kaimi** [comment]
Still using v1.0.3, the latest code was grabbed fine with whitelisting enabled. Gonna update to v1.0.4 now.
