### ISSUE TITLE
Copying codes brings an error message.

### ISSUE THREAD

**Issue by terininetails** [Lumbridge/SmiteMixerCodeRedeemer#13]
This doesn't happen every time, but I'd say about half of the times I click "copy selected code to clipboard", I receive an error dialog: 

> Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.
> 
> Requested Clipboard operation did not succeed.

Oddly enough, the code does still copy to the clipboard after I click continue. 

I've attached the details dump. 
[crashdump.txt](https://github.com/Lumbridge/SmiteMixerCodeRedeemer/files/1861440/crashdump.txt)

**Comment by Lumbridge** [comment]
Interesting, thanks for bringing this to my attention! Will be fixed in v1.0.5.
