### ISSUE TITLE
Feature request: automating the whole 64bit / DX11 thing

### ISSUE THREAD

**Issue by kaimi** [Lumbridge/SmiteMixerCodeRedeemer#15]
So I tried familiarising myself with the code that does the window title matching. I thought there has to be a way to not make the user decide which version of Smite they are running.

https://github.com/Lumbridge/SmiteMixerCodeRedeemer/blob/master/SmiteMixerCodeGrabberGUI/Properties/Settings.settings#L38
https://github.com/Lumbridge/SmiteMixerCodeRedeemer/blob/53addf7e3d390416eae2d161d5adca8b3a8505e9/SmiteMixerCodeGrabberGUI/Classes/DynamicResolution.cs#L79
https://github.com/Lumbridge/SmiteMixerCodeRedeemer/blob/703ba2a0b4ef62afd5fb7e271436486ee355b86e/Dolphin%20Script/Classes/Backend/WindowControl.cs#L100

As I said in #14, I don’t really know .Net, so I wasn’t able to solve this for myself and just open a pull request. Is there a way to somehow search by regex / glob instead of a simple String? If not, you could always go and check for all 4 combinations of 32/64 bit and DX 9/11, but that’s kinda clunky.

**Comment by kaimi** [comment]
Related: some kind of “this is how to contribute” readme would be appreciated. I’m usually working on Linux so this whole .Net thing is pretty foreign to me, but I’d like to do some stuff by myself if that’s OK :)

**Comment by Lumbridge** [comment]
I appreciate all of your input! I've implemented the automatic window detection you suggested. Once I refactor the code so it's less messy I can write a concise documentation of the project so others can expand/add/change it easier 👍

**Comment by kaimi** [comment]
Nice, thanks!
