### ISSUE TITLE
AFK

### ISSUE THREAD

**Issue by nkellogg07** [Lumbridge/SmiteMixerCodeRedeemer#16]
Using the AFK mode on 64-Bit DX11 does not automatically redeem the code in smite.  Focus on the Smite window, then a pause w/ no code redemption.  Have to copy from redeemer and redeem manually. :(

**Comment by Lumbridge** [comment]
Will see if i can replicate this issue and get back to you.

**Comment by Lumbridge** [comment]
Just tried it on two machines (laptop & pc) both using fresh v1.0.6 downloads and it worked perfectly.  
Try deleting all files (including .dlls inside the folder) and download fresh from ![here](https://github.com/Lumbridge/SmiteMixerCodeRedeemer/releases/download/v1.0.6/Smite.Mixer.Code.Redeemer.v1.0.6.zip)

**Comment by nkellogg07** [comment]
Ok. Will try. I am using v1.0.5 at the moment.

Thanks

**Comment by Lumbridge** [comment]
v1.0.5 was broken but is now fixed and stable 😀

**Comment by nkellogg07** [comment]
Fixed in 1.0.6 Thank!
