### ISSUE TITLE
Smite isnt minimised after the code is redeemed

### ISSUE THREAD

**Issue by leadheadfred** [Lumbridge/SmiteMixerCodeRedeemer#17]
this isnt so much an issue, but its a suggestion that i think would be quite simple to implement, and would be quite useful if somebody is unable to access the computer but using it (eg watching netlfix in bed)

**Comment by Lumbridge** [comment]
Will look into implementing this soon.

**Comment by Lumbridge** [comment]
Implemented in v1.0.7 (releasing around 17:00 BST 06/04/2018).
