### ISSUE TITLE
"Microsoft .NET Framework" Error

### ISSUE THREAD

**Issue by yungwaifu** [Lumbridge/SmiteMixerCodeRedeemer#19]
It says 
"Unhandled exception has occurred in your application. If you click 
Continue, the application will ignore this error and attempt to continue. If
you click Quit, the application will close immediately.

Could not load file or assembly 'MixerChar, Version=1.0.0.0.
Culture=neutral, PublicKeyToken=null' or one of its dependencies. The
system cannot find the file specified."

It had been working for me for a while, and only happened when I tried to download and use the newest version. It now does this whenever I run either v1.0.2 or v1.0.6. A message comes up before the one above saying its unsafe and an .EXE. 

The program will still run, but there are no whitelisted users in the box and nothing in the big box at the bottom. It still inputs codes into smite, but there are no codes in active or expired. Also, some of the codes it puts in dont work.

Not sure if its something on my end, but it seems likely since it had been working for a while.

**Comment by Lumbridge** [comment]
Delete all files and download again, let me know if it fixes it.

**Comment by yungwaifu** [comment]
It didn’t fix it, same errors. I can send screenshots if you need.

**Comment by Lumbridge** [comment]
Screenshots would help, you can also try installing the latest .Net Framework from [here](https://www.microsoft.com/net/download/thank-you/net471?survey=false).
Also let me know your OS version.

**Comment by yungwaifu** [comment]
I tried installing the newest .Net framework and its still not working. I'm
using Windows 10. Thanks for helping out.

**Comment by Lumbridge** [comment]
@yungwaifu if you can get me the error message that appears in the exception box that'd help a lot.

**Comment by yungwaifu** [comment]
Where is the exception box?

**Comment by Lumbridge** [comment]
In your original post you said that you got an unhandled exception, when this happens a box should appear, copy everything inside it and post it here.

**Comment by yungwaifu** [comment]
If it isnt one of the images i sent in the last email, im not sure i have
seen it. im attaching a screenshot of what the program looks like when run
after going through the error messages attached in the last email.

**Comment by Lumbridge** [comment]
@yungwaifu I can't see any screenshots in this thread? Could you upload them to an [Imgur](https://imgur.com/upload) album and put the link here?

**Comment by yungwaifu** [comment]
Here's what was in the exception box:

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly
'MixerChat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one
of its dependencies. The system cannot find the file specified.
File name: 'MixerChat, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=null'
   at SmiteMixerCodeGrabberGUI.MainForm.MainForm_Load(Object sender,
EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value
[HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind
failure logging.
To turn this feature off, remove the registry value
[HKLM\Software\Microsoft\Fusion!EnableLog].



************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase:
file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Smite Mixer Code Grabber
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase:
file:///C:/Users/franke19116/AppData/Local/Temp/wz0624/Smite%20Mixer%20Code%20Redeemer%20v1.0.6/Smite%20Mixer%20Code%20Grabber.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase:
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Lumbridge** [comment]
@yungwaifu The error is due to the program not finding MixerChat.dll, make sure all .dll files are in the same directory as the .exe.
Your files should be setup as seen in the image below:
![Imgur](https://i.imgur.com/WEsCSm7.png)  
(It seems you're viewing this thread through email so if you can't see the image use this link: https://i.imgur.com/WEsCSm7.png).  
  
P.s. Version v1.0.7 is now available [here](https://github.com/Lumbridge/SmiteMixerCodeRedeemer/releases/download/v1.0.7/Smite.Mixer.Code.Redeemer.v1.0.7.zip).

**Comment by yungwaifu** [comment]
Thanks!

**Comment by Lumbridge** [comment]
@yungwaifu All fixed then?

**Comment by Lumbridge** [comment]
Assuming this is fixed, closed (for now?).
