### ISSUE TITLE
automated redemption broken (on non-QWERTY keyboard layouts?)

### ISSUE THREAD

**Issue by kaimi** [Lumbridge/SmiteMixerCodeRedeemer#2]
When trying to redeem a code, it puts `9claimpromotion` into the Smite chatbox instead of `/claimpromotion`. I guess that’s caused by the non-QWERTY layout I’m using (http://neo-layout.org).

Instead of trying to actually type a `/`, I guess you should paste it into the chatbox just like you are doing with the actual code.

**Comment by Lumbridge** [comment]
Should be fixed, will use an OEM forward slash in the next version.
