### ISSUE TITLE
Redeem function stopped working again.

### ISSUE THREAD

**Issue by ThePenitence** [Lumbridge/SmiteMixerCodeRedeemer#20]
So I know this was fixed after 1.0.4, and it's been working fine, but now today it's not. Same issue as before, press the redeem button, it switches to Smite to do the redeem command but doesn't do it and changes the redeemed value in the UI to True.

**Comment by nkellogg07** [comment]
I have the same issue in 1.0.6.  Codes are not being redeemed in Smite.  The Smite window flashes but does not maximize and the code is on redeemed, even though the code is tagged as redeemed in Grabber.

**Comment by ThePenitence** [comment]
Okay now today it's working again. Not sure what might have caused it to not work yesterday? The game's window settings or any other settings weren't changed. The same version of the code grabber was being used. Annoying when things that should be working just don't lol

**Comment by kaimi** [comment]
> Not sure what might have caused it to not work yesterday?

PEBCAK? :)

**Comment by Lumbridge** [comment]
@kaimi haha possibly 😄 there is a crash I’ve fixed which hasn’t been built for a release yet though, will be built & released soon.
