### ISSUE TITLE
AFK & Redeem Code

### ISSUE THREAD

**Issue by nkellogg07** [Lumbridge/SmiteMixerCodeRedeemer#21]
Updated to v1.0.7 and now the AFK mode and Redeem Code do not work.  I have to copy the code and paste it in order to redeem

**Comment by kaimi** [comment]
Worksforme™

**Comment by nkellogg07** [comment]
I am happy for you.... I does not work for me.  It grabs the code and that is it.  AFK Mode does not work anymore.

**Comment by Lumbridge** [comment]
@nkellogg07 Make sure you delete all files (including .dlls) when upgrading to the newest version.

**Comment by nkellogg07** [comment]
Completely deleted from my computer.  Used cCleaner to remove any registry entries, ran windows update, rebooted, and tried running Code Grabber.  Still same outcome.  It grabs the codes just fin, but will not redeem them in AFK Mode or by using the Redeem Selected Code button.  I have to copy and paste to redeeem.

**Comment by Lumbridge** [comment]
@nkellogg07 Try run as Admin.

**Comment by nkellogg07** [comment]
I am trying v1.0.7.1 first then I will try as admin. Let you know in a bit.

**Comment by nkellogg07** [comment]
Running as Administrator works.

**Comment by Lumbridge** [comment]
Cool, enjoy.

**Comment by kaimi** [comment]
> Running as Administrator works.

That is a really bad (and potentially dangerous) workaround. If everything is working normally, that shouldn’t make things work that previously didn’t.

The only thing I can think of off the top off my head causing this is if you were running Smite as Administrator. Don’t run Smite as Administrator.

**Comment by nkellogg07** [comment]
Thanks Kaimi. Was debugging discord so had Smite running as admin. Works fine as long as both are running in the same mode.
