### ISSUE TITLE
Program doesn't work?

### ISSUE THREAD

**Issue by brothan323** [Lumbridge/SmiteMixerCodeRedeemer#24]
This program is very weird. Sometimes it'll redeem codes, sometimes it won't. Like today(saturday the 14th,) it redeemed all the mixer chest codes, BUT NOT THE ODYSSEY CHEST!!!WHY!?!?!?! This program is serious ass. Yesterday it didn't even redeem ANY codes. No idea what is going on. Program is running in admin mode, smite is fullscreen borderless. I run a test code to make sure the program works before I AFK.

EDit: The odyssey chest code was this: APYSC8F85AB180326 and your program does NOT have this code in the little history boix on the bottom of the screen OR on the expired list. I think your program can't read odyssey chest codes.

**Comment by Lumbridge** [comment]
Are you using Whitelist?
