### ISSUE TITLE
Code matching specified criteria was observed Nuissance

### ISSUE THREAD

**Issue by bryancpe** [Lumbridge/SmiteMixerCodeRedeemer#27]
When white listed is checked getting Code matching specified criteria was observed from other users is a nuissance. Prevent sending out messages unless the user is on the whitelist. Especially if all other limitations are turned off like zero size and not starting with AP are removed then all messages output by all users will be listed a probable codes.

**Comment by Lumbridge** [comment]
WhiteList is no longer optional and should only contain Scottybot, make sure you're using v1.0.8. Console output is there for logging purposes.
