### ISSUE TITLE
Issue when they post the code without capitals

### ISSUE THREAD

**Issue by EggFriedCheese** [Lumbridge/SmiteMixerCodeRedeemer#28]
Auvey was offline today, and the codes were posted by F.

He didn't post them with 2x capitals, therefore the program didn't pick them up. May need to change the algorithm slightly to incorporate it.

**Comment by drecli** [comment]
I dont think thats the problem. The problem i got is : 3 times, i got a notification. The programe tried to redeem it : doesnt work. Its like a flare, a bot trap : he tries to reedem it and it doesnt work. Some minutes later, they send the true code but the program seems blocked by the false one and do not even see the right one which is not reedemed.

**Comment by Lumbridge** [comment]
Updated to fix this.

**Comment by EggFriedCheese** [comment]
Wow, the list of blacklisted words is huge lol. Good job.

**Comment by Lumbridge** [comment]
It should mean that when scottybot writes a message now, the program will split his sentence into individual words, pick out the word(s) not on the blacklist and add those to active codes.
