### ISSUE TITLE
Can't scroll through long Active/Expired code lists.

### ISSUE THREAD

**Issue by ThePenitence** [Lumbridge/SmiteMixerCodeRedeemer#30]
Hey great job with keeping up with updates. I just want to point out an issue that if one has too many codes to fit in the list for Active/Expired and scrolling becomes an option, the list flickers every second the timers on the codes change and because of it if you're trying to scroll the list it keeps resetting the position to the top of the list. If you're not sure how to fix that, you could also make the program window size adjustable so the fields for Active/Expired could be bigger which would also deal with the problem. It would be cool if the program could maximize to fill the entire screen.

**Comment by kaimi** [comment]
see #29

**Comment by Lumbridge** [comment]
Cheers @kaimi 

@ThePenitence Will be making the window resizable in the next version, for now use the work around @kaimi referenced. Cheers 👍
