### ISSUE TITLE
Codes

### ISSUE THREAD

**Issue by nkellogg07** [Lumbridge/SmiteMixerCodeRedeemer#37]
The last three codes today were not grabbed.  The following is the format the used:

Scottybot Most Recent Code: SmiteMastersFTW ------ AnEnigma ------ BlameCooper

**Comment by Lumbridge** [comment]
Strange, keep me posted of any further problems.

________________________________

**Comment by kaimi** [comment]
I also missed the last day of codes; I accidentally started the grabber twice and closed one instance. Is there one background process that’s garbbing codes and that got shut down by closing the one UI window?

**Comment by nkellogg07** [comment]
No. It was doing some funky stuff. I would skip codes, then try to redeem
the same code 5 times. I stopped the grabber and restarted and it seemed to
work after that.  There was no clear cause.

Thanks,

Nicholas B. Kellogg
<http://www.linkedin.com/in/nicholasbkellogg>

**Comment by Lumbridge** [comment]
Yeah @kaimi when closing the UI it’ll end all background processes program; I should probably make this more robust in the future so this doesn’t happen again. I return home on Monday so will look at cleaning up the code and fixing bugs. Cheers guys.

**Comment by nkellogg07** [comment]
Issue has not reoccurred.
