### ISSUE TITLE
Redeem All, Clear Active, etc. does not work at all and will not trigger a renewal 

### ISSUE THREAD

**Issue by fragmi** [Lumbridge/SmiteMixerCodeRedeemer#39]
Redeem all/Clear Active/Clear Expired do not appear to function properly and often do not work at all or acknowledge their action...

**Comment by Lumbridge** [comment]
All working for me - haven't had this complaint and the build has been live for ages.

Edit: Could you give more info?
- How long have you been using the program?
- Using Windows OS?
- Smite client shouldn't be running as admin.

**Comment by Lumbridge** [comment]
Closing due to no further info.
