### ISSUE TITLE
Feature request: sound-only notifications

### ISSUE THREAD

**Issue by kaimi** [Lumbridge/SmiteMixerCodeRedeemer#4]
I like to be reminded, but I don’t need the popup window; so having only the sound notification would be a nice thing.

**Comment by Lumbridge** [comment]
Done, thanks for the contribution!

**Comment by kaimi** [comment]
You should maybe change the label on the option to make it clear that way now.

**Comment by Lumbridge** [comment]
Will do, thanks for the reminder.
