### ISSUE TITLE
Redeem stopped working after v1.0.1

### ISSUE THREAD

**Issue by ThePenitence** [Lumbridge/SmiteMixerCodeRedeemer#7]
It was working perfectly when I first started using, then took that update for fixing the notifications bug, it was fine for awhile, then it stopped working after I rebooted my computer. It still switches to Smite, but it doesn't type anything anymore.

**Comment by Lumbridge** [comment]
Should be fixed in version v1.0.3 coming soon, unable to test currently because the game is down :(
